"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class legcontrol_t(object):
    __slots__ = ["num_joints", "lcm_timestamp", "q", "p", "qd", "v", "tau_est"]

    __typenames__ = ["int8_t", "double", "double", "double", "double", "double", "double"]

    __dimensions__ = [None, None, ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"], ["num_joints"]]

    def __init__(self):
        self.num_joints = 0
        self.lcm_timestamp = 0.0
        self.q = []
        self.p = []
        self.qd = []
        self.v = []
        self.tau_est = []

    def encode(self):
        buf = BytesIO()
        buf.write(legcontrol_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bd", self.num_joints, self.lcm_timestamp))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.q[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.p[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.qd[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.v[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.tau_est[:self.num_joints]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != legcontrol_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return legcontrol_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = legcontrol_t()
        self.num_joints, self.lcm_timestamp = struct.unpack(">bd", buf.read(9))
        self.q = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.p = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.qd = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.v = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.tau_est = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if legcontrol_t in parents: return 0
        tmphash = (0x8f436a7d415efc8d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if legcontrol_t._packed_fingerprint is None:
            legcontrol_t._packed_fingerprint = struct.pack(">Q", legcontrol_t._get_hash_recursive([]))
        return legcontrol_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

